name: Merge the current PR
on:
  repository_dispatch:
    types:
      - merge-command

jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest

    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.12.0
        env:
          GITHUB_TOKEN: "${{ secrets.CI_TOKEN }}"
          MERGE_LABELS: "!hold"
          MERGE_METHOD: "merge"
          MERGE_RETRY_SLEEP: "30000"  # 30 seconds
          UPDATE_LABELS: "!hold"
          UPDATE_METHOD: "rebase"
