name: Build and publish the docker images
on:
  repository_dispatch:
    types:
      - deploy-staging-command

jobs:
  configure:
    name: Preliminary configuration
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.configure.outputs.ref }}
      repo-suffix: ${{ steps.configure.outputs.repo-suffix }}
      repo-push: ${{ steps.configure.outputs.repo-push }}

    steps:
      - name: Configure
        id: configure
        run: |
          echo "::set-output name=ref::11d2361090cda99b857fe0094f199fadf38930b6"

  trigger-events-deploy-staging:
    name: Trigger events upon /deploy-staging comment
    runs-on: ubuntu-latest
    needs:
      - configure
    if: github.event_name == 'repository_dispatch'

    steps:
      - name: Notify Event to CrownOps
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: netgroup-polito/CrownOps
          event-type: deploy-staging-event
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "pr-number": "${{ github.event.client_payload.github.payload.issue.number }}",
              "tag": "${{ needs.configure.outputs.ref }}"
            }

      - name: Report status as reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: 'hooray'
