name: Check linting
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  python-lint:
    name: Lint python files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Check linting
        uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failIf: any
        env:
          LINTLY_PR: ${{ github.event.pull_request.number }}
          LINTLY_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
