name: Rebase
on:
  repository_dispatch:
    types:
      - rebase-command

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Automatic rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
          PR_NUMBER: ${{ github.event.client_payload.github.payload.issue.number }}

      - name: Set the reaction for the comment
        id: rebase_reaction
        run: |
          [[ ${{ job.status }} == 'success' ]] && \
            echo ::set-output name=reaction::hooray || \
            echo ::set-output name=reaction::confused
        if: always()

      - name: Report status as reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: '${{ steps.rebase_reaction.outputs.reaction }}'
        if: always()
